apiVersion: v1
kind: Service
metadata:
  name: {{ include "nipio.fullname" . }}
  labels:
    {{- include "nipio.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: dns-udp
      protocol: UDP
      name: nip-dns
  selector:
    {{- include "nipio.selectorLabels" . | nindent 4 }}
